name: Bug Report
description: Report a bug or unexpected behavior in Rollout
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. With config '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Rollout is affected?
      options:
        - CLI
        - Task/Dataset Loading
        - Docker Provider
        - Apple Container Provider
        - Modal Provider
        - Trial Executor
        - Configuration
        - Registry
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Rollout Version
      description: Output of `rollout --version` or commit hash
      placeholder: v0.1.0 or abc1234

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: Paste any relevant logs or error messages.
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant job.yaml or task.toml configuration (if applicable).
      render: yaml

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem.
