name: Codebase Improvement
description: Suggest improvements to code quality, tooling, or developer experience
title: "[Improvement]: "
labels: ["improvement"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest improvements to the codebase that enhance quality, maintainability, or developer experience.

  - type: dropdown
    id: type
    attributes:
      label: Type of Improvement
      options:
        - Linting / Static Analysis
        - Testing
        - Build Scripts / Tooling
        - Code Refactoring
        - CI/CD Pipeline
        - Developer Experience
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What improvement would you like to see?
      placeholder: I would like to add/change...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this improvement valuable? What problem does it solve?
      placeholder: This would help by...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Suggested Implementation
      description: Any ideas on how this could be implemented?
      placeholder: We could use...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, references, or examples.
