name: Documentation Update
description: Suggest improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the documentation!

  - type: dropdown
    id: type
    attributes:
      label: Type of Update
      options:
        - Fix incorrect information
        - Add missing information
        - Improve clarity
        - Add examples
        - Fix typos
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Which file or section needs updating?
      placeholder: README.md, SPEC.md, ARCHITECTURE.md, etc.
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Content
      description: What does the documentation currently say (if applicable)?

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Change
      description: What should the documentation say instead?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or references.
