name: Feature Enhancement
description: Suggest a new feature or enhancement for Rollout
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve or the use case it enables.
      placeholder: This would help when...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Rollout does this relate to?
      options:
        - CLI
        - Task/Dataset Loading
        - Docker Provider
        - Apple Container Provider
        - Modal Provider
        - Trial Executor
        - Configuration
        - Registry
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I also considered...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
